### PR TITLE
Update to work with new APIs

### LINKED ISSUE #8: No longer working
It looks like this package no longer works with recent versions of atom. Checked atom-spotify and it appears to have a similar issue ( https://github.com/jakemarsh/atom-spotify/issues/14 )... but I don't use spotify.

The current track doesn't show in the status line and none of the commands seem to have any effect.

Atom version: 0.169.0
Rdio Version: 2.38
Mac OS 10.10.1

### PR DESCRIPTION
**Pull request by joshua**
Now works with Atom v1.0.0

Should resolve #8, #9 and #10.

### CODE REVIEW

**Comment by EtienneLem** [comment]
Holy moly!

I’ll check ASAP :dancer:

**Comment by joshua** [comment]
Should now also resolve #7 and #11.

**Comment by EtienneLem** [comment]
Thank you so much, preparing release 0.6 as we speak.

**Comment by michaelhelmick** [comment]
Thank you!! :cake:

**Pull request merged**
